name: python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.dev }}
          DOCKER_PASSWORD: ${{ secrets.dckr_pat_tnWd7G_YwZgRzvXHFQyyC-XyvKY }}
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker image build -t dev/python:$TAG .
          docker login -u dev -p dckr_pat_tnWd7G_YwZgRzvXHFQyyC-XyvKY
          docker tag dev/python:$TAG vijjuvijaylaxmi/python:latest
          docker push dev/python:$TAG
          docker push dev/python:latest
